// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using DataBaseFirst.Data.Data.Configurations;
using DataBaseFirst.Data.Models;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Reflection;
#nullable enable

namespace DataBaseFirst.Data.Data;

public partial class NorthwindContext : DbContext
{
    
    public NorthwindContext(DbContextOptions<NorthwindContext> options)
        : base(options)
    {
    }

    public NorthwindContext()
    {
    }

    public virtual DbSet<Category> Categories { get; set; }

    public virtual DbSet<Customer> Customers { get; set; }

    public virtual DbSet<Product> Products { get; set; }

    public virtual DbSet<ProductsAboveAveragePrice> ProductsAboveAveragePrices { get; set; }

    public virtual DbSet<Supplier> Suppliers { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    => optionsBuilder.UseSqlServer("Server = . ; Database = Northwind ; Trusted_Connection = true ; TrustServerCertificate = true");

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        //modelBuilder.ApplyConfiguration(new Configurations.CategoryConfiguration());
        //modelBuilder.ApplyConfiguration(new Configurations.CustomerConfiguration());
        //modelBuilder.ApplyConfiguration(new Configurations.ProductConfiguration());
        //modelBuilder.ApplyConfiguration(new Configurations.ProductsAboveAveragePriceConfiguration());
        //modelBuilder.ApplyConfiguration(new Configurations.SupplierConfiguration());
        modelBuilder.ApplyConfigurationsFromAssembly(Assembly.GetExecutingAssembly());

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}
